// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/rpcheader.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   []byte                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MethodName    []byte                 `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	ArgsSize      uint32                 `protobuf:"varint,3,opt,name=args_size,json=argsSize,proto3" json:"args_size,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	DeadlineMs    int64                  `protobuf:"varint,5,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcHeader) Reset() {
	*x = RpcHeader{}
	mi := &file_proto_rpcheader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHeader) ProtoMessage() {}

func (x *RpcHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpcheader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHeader.ProtoReflect.Descriptor instead.
func (*RpcHeader) Descriptor() ([]byte, []int) {
	return file_proto_rpcheader_proto_rawDescGZIP(), []int{0}
}

func (x *RpcHeader) GetServiceName() []byte {
	if x != nil {
		return x.ServiceName
	}
	return nil
}

func (x *RpcHeader) GetMethodName() []byte {
	if x != nil {
		return x.MethodName
	}
	return nil
}

func (x *RpcHeader) GetArgsSize() uint32 {
	if x != nil {
		return x.ArgsSize
	}
	return 0
}

func (x *RpcHeader) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RpcHeader) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *RpcHeader) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_rpcheader_proto protoreflect.FileDescriptor

const file_proto_rpcheader_proto_rawDesc = "" +
	"\n" +
	"\x15proto/rpcheader.proto\x12\x05mprpc\"\xa1\x02\n" +
	"\tRpcHeader\x12!\n" +
	"\fservice_name\x18\x01 \x01(\fR\vserviceName\x12\x1f\n" +
	"\vmethod_name\x18\x02 \x01(\fR\n" +
	"methodName\x12\x1b\n" +
	"\targs_size\x18\x03 \x01(\rR\bargsSize\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x1f\n" +
	"\vdeadline_ms\x18\x05 \x01(\x03R\n" +
	"deadlineMs\x12:\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1e.mprpc.RpcHeader.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x14Z\x12go-rpc/proto;protob\x06proto3"

var (
	file_proto_rpcheader_proto_rawDescOnce sync.Once
	file_proto_rpcheader_proto_rawDescData []byte
)

func file_proto_rpcheader_proto_rawDescGZIP() []byte {
	file_proto_rpcheader_proto_rawDescOnce.Do(func() {
		file_proto_rpcheader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rpcheader_proto_rawDesc), len(file_proto_rpcheader_proto_rawDesc)))
	})
	return file_proto_rpcheader_proto_rawDescData
}

var file_proto_rpcheader_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rpcheader_proto_goTypes = []any{
	(*RpcHeader)(nil), // 0: mprpc.RpcHeader
	nil,               // 1: mprpc.RpcHeader.MetadataEntry
}
var file_proto_rpcheader_proto_depIdxs = []int32{
	1, // 0: mprpc.RpcHeader.metadata:type_name -> mprpc.RpcHeader.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rpcheader_proto_init() }
func file_proto_rpcheader_proto_init() {
	if File_proto_rpcheader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rpcheader_proto_rawDesc), len(file_proto_rpcheader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rpcheader_proto_goTypes,
		DependencyIndexes: file_proto_rpcheader_proto_depIdxs,
		MessageInfos:      file_proto_rpcheader_proto_msgTypes,
	}.Build()
	File_proto_rpcheader_proto = out.File
	file_proto_rpcheader_proto_goTypes = nil
	file_proto_rpcheader_proto_depIdxs = nil
}
